---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/argocd/bootstrap/root
    repoURL: https://github.com/chrismgonzalez/home-kubernetes-service
    targetRevision: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 1m
        maxDuration: 5m
        factor: 2
    syncOptions:
    - CreateNamespace=true