---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-0
  namespace: flux-system
spec:
  dependsOn:
    - name: sidero
    - name: px-operator
  path: ./kubernetes/apps/clusters/cluster-0/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: px-kaas
  interval: 5m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false