apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-csi-plugin-controller
  namespace: csi-proxmox
  labels:
    helm.sh/chart: proxmox-csi-plugin-0.1.0
    app.kubernetes.io/name: proxmox-csi-plugin
    app.kubernetes.io/instance: proxmox-csi-plugin
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proxmox-csi-plugin
      app.kubernetes.io/instance: proxmox-csi-plugin
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxmox-csi-plugin
        app.kubernetes.io/instance: proxmox-csi-plugin
        app.kubernetes.io/component: controller
    spec:
      priorityClassName: system-cluster-critical
      enableServiceLinks: false
      serviceAccountName: proxmox-csi-plugin-controller
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: proxmox-csi-plugin-controller
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: "ghcr.io/sergelogvinov/proxmox-csi-controller:edge"
          imagePullPolicy: Always
          args:
            - "-v=5"
            - "--csi-address=unix:///csi/csi.sock"
            - "--cloud-config=/etc/proxmox/config.yaml"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: cloud-config
              mountPath: /etc/proxmox/
        - name: csi-attacher
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: "registry.k8s.io/sig-storage/csi-attacher:v4.2.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-v=5"
            - "--csi-address=unix:///csi/csi.sock"
            - "--timeout=3m"
            - "--leader-election"
            - "--default-fstype=ext4"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources: 
            requests:
              cpu: 10m
              memory: 16Mi
        - name: csi-provisioner
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: "registry.k8s.io/sig-storage/csi-provisioner:v3.4.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-v=5"
            - "--csi-address=unix:///csi/csi.sock"
            - "--timeout=3m"
            - "--leader-election"
            - "--default-fstype=ext4"
            - "--feature-gates=Topology=True"
            - "--enable-capacity"
            - "--capacity-ownerref-level=2"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources: 
            requests:
              cpu: 10m
              memory: 16Mi
        - name: csi-resizer
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: "registry.k8s.io/sig-storage/csi-resizer:v1.7.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-v=5"
            - "--csi-address=unix:///csi/csi.sock"
            - "--timeout=3m"
            - "--handle-volume-inuse-error=false"
            - "--leader-election"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources: 
            requests:
              cpu: 10m
              memory: 16Mi
        - name: liveness-probe
          image: "registry.k8s.io/sig-storage/livenessprobe:v2.9.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-v=5"
            - "--csi-address=unix:///csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources: 
            requests:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: cloud-config
          secret:
            secretName: proxmox-csi-plugin
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane