---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxmox-csi-plugin-controller
  namespace: csi-proxmox
  labels:
    helm.sh/chart: proxmox-csi-plugin-0.1.0
    app.kubernetes.io/name: proxmox-csi-plugin
    app.kubernetes.io/instance: proxmox-csi-plugin
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxmox-csi-plugin-node
  namespace: csi-proxmox
  labels:
    helm.sh/chart: proxmox-csi-plugin-0.1.0
    app.kubernetes.io/name: proxmox-csi-plugin
    app.kubernetes.io/instance: proxmox-csi-plugin
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm