apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-storage
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: {{ .Values.storage.storage_ext4 }}
  ssd: "false"