allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-lvm
parameters:
  csi.storage.k8s.io/fstype: ext4
  # blockSize: "1024"
  # inodeSize: "512"
  #
  storage: vm-data
  # diskIOPS: "400"
  # diskMBps: "120"
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer