{{- if .Values.ca.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: talos-cluster-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: talos-cluster-self-signed-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: root-secret
{{- end }}