apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-talos-dhcp-server
  namespace: kube-system
  labels:
    helm.sh/chart: talos-dhcp-server-0.0.9
    app.kubernetes.io/name: talos-dhcp-server
    app.kubernetes.io/instance: dhcp
    app.kubernetes.io/version: "0.0.9"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: talos-dhcp-server
      app.kubernetes.io/instance: dhcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: talos-dhcp-server
        app.kubernetes.io/instance: dhcp
    spec:
      serviceAccountName: dhcp-talos-dhcp-server
      hostNetwork: true
      containers:
        - name: talos-dhcp-server
          #command: ["sleep", "infinity"]
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          image: "crashntech/talos-dhcp-server:0.0.9"
          imagePullPolicy: IfNotPresent
          volumeMounts: 
            - mountPath: /var/lib/dhcp/
              name: dhcpd-leases
            - mountPath: /etc/dhcp/dhcpd.conf
              name: config
              subPath: dhcpd.conf
          ports:
            - name: dhcp
              containerPort: 67
              protocol: UDP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: dhcpd-leases
          emptyDir:
            sizeLimit: 100Mi
        - name: config
          secret:
            secretName: dhcp-talos-dhcp-server