apiVersion: v1
kind: Secret
metadata:
  name: dhcp-talos-dhcp-server
  namespace: kube-system
type: Opaque
stringData: 
  dhcpd.conf: |-
    env SIDERO_ENDPOINT=10.1.1.25
    
    default-lease-time 600;
    max-lease-time 7200;
    ddns-update-style none;
    authoritative;
    log-facility local7;
    update-conflict-detection true;
    subnet 10.244.0.0 netmask 255.255.0.0 {
    }
    subnet 10.1.1.0 netmask 255.255.255.0 {
      range 10.1.1.50 10.1.1.180;
      option subnet-mask 255.255.255.0;
      option broadcast-address 10.1.1.250;
      option routers 10.1.1.1;
      option domain-name-servers 1.1.1.1, 1.0.0.1;
      option domain-name "gonzonet.live";
      default-lease-time 600;
      max-lease-time 7200;
    }
    allow bootp;
    allow booting;
  
  
    # IP address for PXE-based TFTP methods
    next-server ${SIDERO_ENDPOINT};
  
    # Configuration for iPXE clients
    class "ipxeclient" {
      match if exists user-class and (option user-class = "iPXE");
      filename "http://${SIDERO_ENDPOINT}:8081/tftp/undionly.kpxe";
    }
  
    # Configuration for legacy BIOS-based PXE boot
    class "biosclients" {
      match if not exists user-class and substring (option vendor-class-identifier, 15, 5) = "00000";
      filename "undionly.kpxe";
    }
  
    # Configuration for UEFI-based PXE boot
    class "pxeclients" {
      match if not exists user-class and substring (option vendor-class-identifier, 0, 9) = "PXEClient";
      filename "ipxe.efi";
    }
  
    # Configuration for UEFI-based HTTP boot
    class "httpclients" {
      match if not exists user-class and substring (option vendor-class-identifier, 0, 10) = "HTTPClient";
      option vendor-class-identifier "HTTPClient";
      filename "http://${SIDERO_ENDPOINT}:8081/tftp/ipxe.efi";
    }