apiVersion: v1
kind: ServiceAccount
metadata:
  name: dhcp-talos-dhcp-server
  namespace: kube-system
  labels:
    helm.sh/chart: talos-dhcp-server-0.0.9
    app.kubernetes.io/name: talos-dhcp-server
    app.kubernetes.io/instance: dhcp
    app.kubernetes.io/version: "0.0.9"
    app.kubernetes.io/managed-by: Helm